name: Build Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install pyinstaller openpyxl
    - run: pyinstaller --onefile --windowed --name "Sistema-Otchetov" --hidden-import=logic --hidden-import=database --hidden-import=export_excel main.py
    - uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/Sistema-Otchetov.exe
